<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class IBMWatsonController extends Controller
{
  public function getToken()
  {
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, "https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?timestamps=true&max_alternatives=3");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $post = array(
        "file" => "@" .realpath("/audio-file.flac")
    );

    $postfields = array('file' => '@audio-file.flac');

    curl_setopt($ch, CURLOPT_POSTFIELDS, $postfields);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_USERPWD, "72637c4c-7a5a-4076-81c4-06393105f669" . ":" . "uMMHPLlCzyvu");

    $headers = array();
    $headers[] = "Content-Type: audio/flac";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    print_r($result);
}
}
